# Generated by Django 5.0.7 on 2024-07-27 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="create_uid",
            new_name="create_by",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="write_uid",
            new_name="write_by",
        ),
        migrations.RenameField(
            model_name="eventregistration",
            old_name="create_uid",
            new_name="create_by",
        ),
        migrations.RenameField(
            model_name="eventregistration",
            old_name="write_uid",
            new_name="write_by",
        ),
    ]
