# Generated by Django 5.0.7 on 2024-07-27 18:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_rename_create_uid_event_create_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="eventregistration",
            unique_together={("guest", "event")},
        ),
    ]
